<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="css" nsURI="http://jve/css" nsPrefix="css">
  <eClassifiers xsi:type="ecore:EClass" name="selector"/>
  <eClassifiers xsi:type="ecore:EClass" name="div" eSuperTypes="#//selector"/>
  <eClassifiers xsi:type="ecore:EClass" name="p" eSuperTypes="#//selector"/>
  <eClassifiers xsi:type="ecore:EClass" name="attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="backgroundColor" eSuperTypes="#//attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="color" eSuperTypes="#//attribute"/>
</ecore:EPackage>
